#!/bin/sh

if ! [ -L /usr/bin/ruby2.5 ]; then
  $(cd /usr/bin/; ln -s ruby ruby2.5)
fi
if id -u ruby-test > /dev/null; then
   userdel ruby-test
fi
useradd ruby-test > /dev/null
PERL5LIB=/usr/lib/perl/5.28.1 su ruby-test -c "tests/run-all $@"
userdel ruby-test > /dev/null
